### PR TITLE
Update docs to reference Java 8's Optional

### PR DESCRIPTION
**Pull request by cjp39**

### CODE REVIEW

**Comment by cjp39** [comment]
For @gm2211 to review. This should be the last one. Thanks, Giulio!

**Comment by hdurer** [comment]
Don't you want to mention the java8 restriction for running tests that this feature introduced?

**Comment by cjp39** [comment]
That's only relevant to someone testing FreeBuilder from source, which this
doc doesn't cover.

**Comment by gm2211** [comment]
I agree with @cjp39 on that.

Just one minor note, the line "optimal yet (e.g.  `if (foo.getX().orElse(null) != null)`  " has only the java.util.Optional "orElse(null)", while all the other examples also keep the guava Optional alternative too.

Apart from that, all looks good to me.

**Comment by cjp39** [comment]
@gm2211 I didn't want to bloat the example too much, and figured since it is marked 'e.g.', it would still get the point across. Does that seem okay?

**Comment by gm2211** [comment]
@cjp39 Yep, I was actually thinking about that too. If you add too many brackets nested you'd make the docs more confusing. 

On second thought it's all good the way it is.

**Pull request merged**
