### PR TITLE
Add custom exception when building instances with unset properties

### PR DESCRIPTION
**Pull request by casidiablo**
The idea is to be able to catch this exception and inspect which properties were unset, mainly to raise  human readable errors if need be.

### CODE REVIEW

**Comment by casidiablo** [comment]
I signed it!

**Comment by chrisalice** [comment]
Unfortunately, FreeBuilder is a compile-time-only library, so we can't ship runtime exception classes. (This is why the integration tests are failing.)

**Comment by chrisalice** [comment]
If you make your exception class available as a separate library, though, FreeBuilder could definitely detect when it's available and generate code that uses it.

**Comment by casidiablo** [comment]
I will give that a try.

**Comment by chrisalice** [comment]
Closing for now. Please do get in touch to discuss the design of your new exception class, as I have some suggestions.

**Comment by casidiablo** [comment]
So far I've contemplated a few alternatives:

- Generate the exception as an inner class of the builder.
- Create an external library with the exception (which I think it's too much).
- Let people manually create the exception class in their projects if they care about this. 
- Let people specify any custom exception that accepts a set of strings and reference that exception via an annotation parameter

What suggestions do you have?

**Pull request closed without merging**
